before_script:
    - apt-get update
    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
    - cd docker-odoo-base

stages:
  - build

build:
  stage: build
  script:
    - docker-compose -f prod.yaml build

