stages:
  - build
#  - test
  - staging
  - promote
  - restart

build:
  stage: build
  script:
    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
    - cd docker-odoo-base
    - docker-compose -f prod.yaml build --no-cache

#test:
#  stage: test
#  script:
#    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
#    - cd docker-odoo-base
#    - docker-compose -f unittest.yaml run --rm odoo unittest extraschool
#  when: on_success

staging:
  stage: staging
  script:
    - docker tag dockerodoobase_odoo docker-staging.imio.be/extraschool-v9
    - docker push docker-staging.imio.be/extraschool-v9:latest
    - mco shell run 'service stagingv9_extraschool stop' -C /role::docker::extraschool::instances$/ -I /staging/
    - mco shell run 'service stagingv9_extraschool start' -C /role::docker::extraschool::instances$/ -I /staging/
    - docker rmi docker-staging.imio.be/extraschool-v9:latest dockerodoobase_odoo
  when: on_success

promote-to-prod:
  stage: promote
  script:
    - docker pull docker-staging.imio.be/extraschool-v9:latest
    - docker tag docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9
    - docker push docker-prod.imio.be/extraschool-v9:latest
    - docker rmi docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9:latest
    - mco shell run 'docker pull docker-prod.imio.be/extraschool-v9:latest' -C /role::docker::extraschool::instances$/ -I /prod/
    - mco shell run 'at -f /srv/docker_scripts/extraschool-update-all-images.sh -t `date -d "tomorrow" +%Y%m%d`0500' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual

restart-Ans:
  stage: restart
  script:
    - mco shell run '/srv/docker_scripts/ans_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual

restart-Braine-l-Alleud:
  stage: restart
  script:
    - mco shell run '/srv/docker_scripts/brainelalleud_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual
  
restart-Dinant:
stage: restart
script:
- mco shell run '/srv/docker_scripts/dinant_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
when: manual

restart-Ferrieres:
  stage: restart
  script:
    - mco shell run '/srv/docker_scripts/ferrieres_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual
  
restart-Ittre:
  stage: restart
  script:
  - mco shell run '/srv/docker_scripts/ittre_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual
  
restart-Rebecq:
  stage: restart
  script:
    - mco shell run '/srv/docker_scripts/rebecq_extraschool/restart.sh' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual
  
restart-Staging:
  stage: restart
  script:
  - mco shell run 'service stagingv9_extraschool stop' -C /role::docker::extraschool::instances$/ -I /staging/
  - mco shell run 'service stagingv9_extraschool start' -C /role::docker::extraschool::instances$/ -I /staging/
  when: manual