stages:
  - build
#  - test
  - staging
  - promote

build:
  stage: build
  script:
    - git clone -b scaffolding91 http://gitlab.imio.be/odoo/docker-odoo-base.git
    - cd docker-odoo-base
    - docker-compose -f prod.yaml build --no-cache
  only:
    - 9.1@odoo/extraschool

#test:
#  stage: test
#  script:
#    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
#    - cd docker-odoo-base
#    - docker-compose run --rm odoo unittest extraschool -i extraschool
#  when: on_success

staging:
  stage: staging
  script:
    - docker tag docker-odoo-base_odoo docker-staging.imio.be/extraschool-v9:9.1
    - docker push docker-staging.imio.be/extraschool-v9:9.1
    - docker rmi docker-staging.imio.be/extraschool-v9:9.1 docker-odoo-base_odoo
    - echo "$(RUNDECK_TOKEN)"
    - curl -v --header "Content-Type:application/json" --header "X-Rundeck-Auth-Token:$(RUNDECK_TOKEN)" https://run.imio.be/api/12/job/6763e023-2dcd-4bca-9510-db8c8d780517/run

  when: on_success
  only:
    - 9.1@odoo/extraschool

promote-to-prod:
  stage: promote
  script:
    - docker pull docker-staging.imio.be/extraschool-v9:9.1
    - docker tag docker-staging.imio.be/extraschool-v9:9.1 docker-prod.imio.be/extraschool-v9:9.1
    - docker push docker-prod.imio.be/extraschool-v9:9.1
    - docker rmi docker-staging.imio.be/extraschool-v9:9.1 docker-prod.imio.be/extraschool-v9:9.1
    - curl --fail -XPOST --header "Content-Type:application/json" --header "X-Rundeck-Auth-Token:$(RUNDECK_TOKEN)" https://run.imio.be/api/12/job/8ea4b91e-2be1-4ea2-ae73-dbd53f3930ef/run
  when: manual
  only:
    - 9.1@odoo/extraschool
