before script:
    - apt-get update
    - git clone -b scaffolding ssh://git@gitlab.imio.be:10022/odoo/docker-odoo-base.git
    - cd docker-odoo-base

stages:
    - build

build:
    stage: build
    script:
      - docker-compose -f prod.yaml build
