before_script:
    - apt-get update
    - apt-get install -y curl
    - rm -Rf docker-odoo-base/
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
#    - eval $(ssh-agent -s)
#    - mkdir -p ~/.ssh
#    - echo "$EXTRASCHOOL_PRIVATE_KEY" > ssh.priv
#    - chmod 600 ssh.priv
#    - cat ssh.priv
#    - ssh-add ssh.priv
    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
    - cd docker-odoo-base

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker-compose -f prod.yaml build

deploy:
  stage: deploy
  script:
    - docker images
