stages:
  - test
  - build
  - staging
  - promote

build:
  stage: build
  script:
    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
    - cd docker-odoo-base
    - chown -R $USER:1000 odoo/auto
    - chmod -R ug+rwX odoo/auto
    - export UID GID="$(id -g $USER)" UMASK="$(umask)"
    - docker-compose -f prod.yaml build --no-cache --remove-orphans

staging:
  stage: staging
  script:
    - docker tag dockerodoobase_odoo docker-staging.imio.be/extraschool-v9
    - docker push docker-staging.imio.be/extraschool-v9:latest
    - mco shell run 'service stagingv9_extraschool stop' -C /role::docker::extraschool::instances$/ -I /staging/
    - mco shell run 'service stagingv9_extraschool start' -C /role::docker::extraschool::instances$/ -I /staging/
    - docker rmi docker-staging.imio.be/extraschool-v9:latest dockerodoobase_odoo
  when: on_success

promote-now:
  stage: promote
  script:
    - docker pull docker-staging.imio.be/extraschool-v9:latest
    - docker tag docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9:latest
    - docker push docker-prod.imio.be/extraschool-v9:latest
    - docker rmi docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9:latest
    - mco shell run 'docker pull docker-prod.imio.be/extraschool-v9:latest' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual

promote-to-prod:
  stage: promote
  script:
    - docker pull docker-staging.imio.be/extraschool-v9:latest
    - docker tag docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9
    - docker push docker-prod.imio.be/extraschool-v9:latest
    - docker rmi docker-staging.imio.be/extraschool-v9:latest docker-prod.imio.be/extraschool-v9:latest
    - mco shell run 'docker pull docker-prod.imio.be/extraschool-v9:latest' -C /role::docker::extraschool::instances$/ -I /prod/
  when: manual
