before_script:
    - apt-get update
    - apt-get install -y curl
    - rm -Rf docker-odoo-base/
    - curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - apt-get install -y mcollective-client

stages:
  - build
  - staging

build:
  stage: build
  script:
    - git clone -b scaffolding http://gitlab.imio.be:10080/odoo/docker-odoo-base.git
    - cd docker-odoo-base
    - docker-compose -f prod.yaml build

staging:
  stage: staging
  script:
    - docker tag dockerodoobase_odoo docker-staging.imio.be/extraschool-v9
    - docker push docker-staging.imio.be/extraschool-v9:latest
