repos:
  -
    repo: local
    hooks:
      -
        id: check-wdb-import
        name: 'Check WDB Import'
        entry: 'python3 check_wdb.py'
        pass_filenames: false
        language: python
        language_version: python3.7
        types:
          - python
        stages:
          - commit
          - push
